EBandPlannerROS:

  max_vel_lin: 0.9
  min_vel_lin: 0.15
  max_vel_th: 1.0
  min_vel_th: 0.3
  max_translational_acceleration: 1.5
  max_rotational_acceleration: 10.0

  differential_drive: true

  eband_min_relative_overlap: 0.7

  eband_external_force_gain: 3.0

  num_iterations_eband_optimization: 4

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2

  Ctrl_Rate: 30

  eband_equilibrium_relative_overshoot: 0.01
  k_damp: 4.0
  k_prop: 3.0
